apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVICE}
  namespace: ${NAMESPACE}
  labels:
    app: ${SERVICE}
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      app: ${SERVICE}
  template:
    metadata:
      labels:
        app: ${SERVICE}
    spec:
      containers:
      - name: ${SERVICE}
        image: ${REGISTRY}/${SERVICE}:${VERSION}
        imagePullPolicy: Always
        resources:
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
          requests:
            cpu: ${CPU_REQUEST}
            memory: ${MEMORY_REQUEST}
        env:
        - name: UV_CACHE_DIR
          value: /tmp/.cache/uv
        - name: UV_NO_SYNC
          value: "1"
        - name: SERVICE_NAME
          value: ${SERVICE}
        - name: VERSION
          value: ${VERSION}
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      volumes:
      - name: tmp-volume
        emptyDir: {}
      securityContext:
        fsGroup: 1000
---
apiVersion: v1
kind: Pod
metadata:
  name: ${SERVICE}-job-${TIMESTAMP}
  namespace: ${NAMESPACE}
  labels:
    app: ${SERVICE}-job
spec:
  containers:
  - name: ${SERVICE}
    image: ${REGISTRY}/${SERVICE}:${VERSION}
    imagePullPolicy: Always
    resources:
      limits:
        cpu: ${CPU_LIMIT}
        memory: ${MEMORY_LIMIT}
      requests:
        cpu: ${CPU_REQUEST}
        memory: ${MEMORY_REQUEST}
    env:
    - name: UV_CACHE_DIR
      value: /tmp/.cache/uv
    - name: UV_NO_SYNC
      value: "1"
    - name: SERVICE_NAME
      value: ${SERVICE}
    - name: VERSION
      value: ${VERSION}
    volumeMounts:
    - name: tmp-volume
      mountPath: /tmp
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - ALL
  volumes:
  - name: tmp-volume
    emptyDir: {}
  restartPolicy: Never
  securityContext:
    fsGroup: 1000